---
- name: install package dependencies
  become: true
  ansible.builtin.apt:
    package:
      - tree
      - docker.io

- name: install global npm packages
  community.general.npm:
    global: true
    name: typescript-language-server
